import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'classic-glazed',
    name: 'Classic Glazed',
    description: 'Our signature glaze made fresh every morning. Light, airy, and perfectly sweet.',
    price: 1.50,
    category: 'glazed',
    emoji: '🍩',
    gradient: 'linear-gradient(135deg, #FFF8DC, #FFE082)',
    popular: true,
  },
  {
    id: 'chocolate-frosted',
    name: 'Chocolate Frosted',
    description: 'Rich chocolate icing over our classic yeast donut. A crowd favorite since day one.',
    price: 1.75,
    category: 'glazed',
    emoji: '🍫',
    gradient: 'linear-gradient(135deg, #F5E6D3, #D4A574)',
  },
  {
    id: 'strawberry-frosted',
    name: 'Strawberry Frosted',
    description: 'Sweet strawberry icing with rainbow sprinkles. A hit with the whole family.',
    price: 1.75,
    category: 'glazed',
    emoji: '🍓',
    gradient: 'linear-gradient(135deg, #FFE4EC, #FFACC7)',
  },
  {
    id: 'texas-honey-butter',
    name: 'Texas Honey Butter',
    description: 'A Texas twist — warm honey butter glaze with a hint of sea salt.',
    price: 2.00,
    category: 'specialty',
    emoji: '🍯',
    gradient: 'linear-gradient(135deg, #FFF8E1, #FFCC02)',
    popular: true,
  },
  {
    id: 'pecan-praline',
    name: 'Pecan Praline',
    description: 'Topped with crushed Texas pecans and a sweet praline glaze. Pure Southern comfort.',
    price: 2.25,
    category: 'specialty',
    emoji: '🌰',
    gradient: 'linear-gradient(135deg, #F5E6D3, #C4956A)',
    popular: true,
  },
  {
    id: 'maple-bacon',
    name: 'Maple Bacon',
    description: 'Maple glaze topped with crispy candied bacon. The one that turns heads.',
    price: 2.50,
    category: 'specialty',
    emoji: '🥓',
    gradient: 'linear-gradient(135deg, #FFF3E0, #FFAB40)',
    popular: true,
  },
  {
    id: 'old-fashioned',
    name: 'Old-Fashioned Cake',
    description: "Dense, crumbly, and perfectly sweet. Grandma's favorite since 1987.",
    price: 1.75,
    category: 'cake',
    emoji: '☕',
    gradient: 'linear-gradient(135deg, #FFFDE7, #FFF9C4)',
  },
  {
    id: 'blueberry-cake',
    name: 'Blueberry Cake',
    description: 'Bursting with fresh blueberry flavor in every bite. A morning classic.',
    price: 1.75,
    category: 'cake',
    emoji: '🫐',
    gradient: 'linear-gradient(135deg, #EDE7F6, #B39DDB)',
  },
  {
    id: 'bavarian-cream',
    name: 'Bavarian Cream',
    description: 'Pillowy soft dough stuffed with silky vanilla cream and dusted with powdered sugar.',
    price: 2.00,
    category: 'filled',
    emoji: '🍮',
    gradient: 'linear-gradient(135deg, #FFFDE7, #FFE57F)',
    popular: true,
  },
  {
    id: 'lemon-filled',
    name: 'Lemon Filled',
    description: 'Bright, tangy lemon curd inside a pillowy donut. Sunshine in every bite.',
    price: 2.00,
    category: 'filled',
    emoji: '🍋',
    gradient: 'linear-gradient(135deg, #F9FBE7, #F0F4C3)',
  },
  {
    id: 'kolache-sausage',
    name: 'Sausage Kolache',
    description: 'A Texas staple. Savory pork sausage wrapped in soft, pillowy kolache dough.',
    price: 2.25,
    category: 'kolache',
    emoji: '🌭',
    gradient: 'linear-gradient(135deg, #FBE9E7, #FFCCBC)',
    popular: true,
  },
  {
    id: 'kolache-cheese',
    name: 'Jalapeño Cheese Kolache',
    description: 'Gooey cheddar and jalapeño wrapped in soft kolache dough. Texas heat, Texas heart.',
    price: 2.50,
    category: 'kolache',
    emoji: '🌶️',
    gradient: 'linear-gradient(135deg, #F1F8E9, #DCEDC8)',
  },
];

export const categoryLabels: Record<string, string> = {
  all: 'All',
  glazed: 'Glazed',
  cake: 'Cake',
  filled: 'Filled',
  specialty: 'Specialty',
  kolache: 'Kolache',
};
